<a href="https://colab.research.google.com/github/mhndlsz/fraud_detection/blob/master/fraud_detection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [3]:
ls

drive/  sample_data/

In [0]:
id_raw_df   =pd.read_csv("drive/My Drive/kaggle/train_identity.csv")
id_trans_df =pd.read_csv("drive/My Drive/kaggle/train_transaction.csv")

In [0]:
import matplotlib.pyplot as plt
import seaborn as sns

In [6]:
id_raw_df.shape

(144233, 41)

In [7]:
id_raw_df.tail()

        TransactionID  id_01  ...  DeviceType                          DeviceInfo
144228        3577521  -15.0  ...      mobile             F3111 Build/33.3.A.1.97
144229        3577526   -5.0  ...      mobile                 A574BL Build/NMF26F
144230        3577529  -20.0  ...      mobile  Moto E (4) Plus Build/NMA26.42-152
144231        3577531   -5.0  ...     desktop                               MacOS
144232        3577534  -45.0  ...      mobile         RNE-L03 Build/HUAWEIRNE-L03

[5 rows x 41 columns]

In [8]:
id_trans_df.shape

(590540, 394)

In [9]:
id_trans_df.tail()

        TransactionID  isFraud  TransactionDT  ...  V337 V338  V339
590535        3577535        0       15811047  ...   NaN  NaN   NaN
590536        3577536        0       15811049  ...   NaN  NaN   NaN
590537        3577537        0       15811079  ...   NaN  NaN   NaN
590538        3577538        0       15811088  ...   NaN  NaN   NaN
590539        3577539        0       15811131  ...   NaN  NaN   NaN

[5 rows x 394 columns]

In [0]:
train_full_df = pd.merge(id_trans_df, id_raw_df, on='TransactionID', how='left')

In [11]:
train_full_df.shape

(590540, 434)

In [12]:
train_full_df.tail()

        TransactionID  isFraud  TransactionDT  ...  id_38 DeviceType  DeviceInfo
590535        3577535        0       15811047  ...    NaN        NaN         NaN
590536        3577536        0       15811049  ...    NaN        NaN         NaN
590537        3577537        0       15811079  ...    NaN        NaN         NaN
590538        3577538        0       15811088  ...    NaN        NaN         NaN
590539        3577539        0       15811131  ...    NaN        NaN         NaN

[5 rows x 434 columns]

In [13]:
len(train_full_df[train_full_df["isFraud"]==1])/len(train_full_df)*100

3.4990009144173126

In [0]:
from sklearn.model_selection import train_test_split

In [0]:
columns_def=pd.DataFrame({"na_count":train_full_df.isnull().sum().sort_values(ascending=False)})
columns_def["per"]=columns_def["na_count"]/len(train_full_df)

In [16]:
train_full_df.shape

(590540, 434)

In [17]:
train_full_df.tail()

        TransactionID  isFraud  TransactionDT  ...  id_38 DeviceType  DeviceInfo
590535        3577535        0       15811047  ...    NaN        NaN         NaN
590536        3577536        0       15811049  ...    NaN        NaN         NaN
590537        3577537        0       15811079  ...    NaN        NaN         NaN
590538        3577538        0       15811088  ...    NaN        NaN         NaN
590539        3577539        0       15811131  ...    NaN        NaN         NaN

[5 rows x 434 columns]

In [0]:
range=[0.05, 0.10 ,0.15, 0.25, 0.40, 0.60, 0.75]

In [19]:
for i in range: 
    print (columns_def[columns_def["per"]<i].shape[0]/train_full_df.shape[1])

0.25806451612903225
0.25806451612903225
0.3686635944700461
0.41935483870967744
0.46543778801843316
0.5207373271889401
0.5207373271889401

In [0]:
limit=0.10

In [0]:
columns_final=columns_def[columns_def["per"]<limit].index 

train_full_df=train_full_df[train_full_df.columns.intersection(columns_final)]

In [22]:
train_full_df.tail()

        TransactionID  isFraud  ...        V320        V321
590535        3577535        0  ...    0.000000    0.000000
590536        3577536        0  ...    0.000000    0.000000
590537        3577537        0  ...    0.000000    0.000000
590538        3577538        0  ...    0.000000    0.000000
590539        3577539        0  ...  279.950012  279.950012

[5 rows x 112 columns]

In [23]:
train_full_df[train_full_df.select_dtypes(include=['object']).columns]

       ProductCD       card4   card6
0              W    discover  credit
1              W  mastercard  credit
2              W        visa   debit
3              W  mastercard   debit
4              H  mastercard  credit
5              W        visa   debit
6              W        visa   debit
7              W        visa   debit
8              H        visa   debit
9              W  mastercard   debit
10             C  mastercard  credit
11             C  mastercard   debit
12             W        visa   debit
13             W        visa   debit
14             W        visa   debit
15             W        visa   debit
16             H        visa   debit
17             H  mastercard  credit
18             W        visa   debit
19             W        visa   debit
20             W  mastercard   debit
21             W  mastercard   debit
22             H        visa  credit
23             W  mastercard   debit
24             W        visa   debit
25             W  mastercard   debit
26             W        visa   debit
27             W        visa   debit
28             W  mastercard   debit
29             W        visa   debit
...          ...         ...     ...
590510         W        visa   debit
590511         W        visa   debit
590512         W        visa  credit
590513         W        visa   debit
590514         W        visa   debit
590515         W        visa   debit
590516         W        visa   debit
590517         W        visa  credit
590518         W        visa   debit
590519         W  mastercard   debit
590520         W        visa   debit
590521         C  mastercard   debit
590522         W        visa   debit
590523         W  mastercard   debit
590524         W  mastercard   debit
590525         W        visa   debit
590526         R        visa  credit
590527         W        visa   debit
590528         W  mastercard  credit
590529         C  mastercard  credit
590530         W  mastercard  credit
590531         R        visa  credit
590532         W  mastercard   debit
590533         W        visa   debit
590534         C  mastercard   debit
590535         W        visa   debit
590536         W  mastercard   debit
590537         W  mastercard   debit
590538         W  mastercard   debit
590539         W  mastercard  credit

[590540 rows x 3 columns]

In [0]:
card6_dummy_df=pd.get_dummies(train_full_df["card6"])

In [25]:
train_full_df.tail()

        TransactionID  isFraud  ...        V320        V321
590535        3577535        0  ...    0.000000    0.000000
590536        3577536        0  ...    0.000000    0.000000
590537        3577537        0  ...    0.000000    0.000000
590538        3577538        0  ...    0.000000    0.000000
590539        3577539        0  ...  279.950012  279.950012

[5 rows x 112 columns]

In [26]:
train_full_df.shape

(590540, 112)

In [0]:
train_full_df=pd.concat([train_full_df,card6_dummy_df],axis=1)

In [28]:
train_full_df[train_full_df.select_dtypes(include=['object']).columns]

       ProductCD       card4   card6
0              W    discover  credit
1              W  mastercard  credit
2              W        visa   debit
3              W  mastercard   debit
4              H  mastercard  credit
5              W        visa   debit
6              W        visa   debit
7              W        visa   debit
8              H        visa   debit
9              W  mastercard   debit
10             C  mastercard  credit
11             C  mastercard   debit
12             W        visa   debit
13             W        visa   debit
14             W        visa   debit
15             W        visa   debit
16             H        visa   debit
17             H  mastercard  credit
18             W        visa   debit
19             W        visa   debit
20             W  mastercard   debit
21             W  mastercard   debit
22             H        visa  credit
23             W  mastercard   debit
24             W        visa   debit
25             W  mastercard   debit
26             W        visa   debit
27             W        visa   debit
28             W  mastercard   debit
29             W        visa   debit
...          ...         ...     ...
590510         W        visa   debit
590511         W        visa   debit
590512         W        visa  credit
590513         W        visa   debit
590514         W        visa   debit
590515         W        visa   debit
590516         W        visa   debit
590517         W        visa  credit
590518         W        visa   debit
590519         W  mastercard   debit
590520         W        visa   debit
590521         C  mastercard   debit
590522         W        visa   debit
590523         W  mastercard   debit
590524         W  mastercard   debit
590525         W        visa   debit
590526         R        visa  credit
590527         W        visa   debit
590528         W  mastercard  credit
590529         C  mastercard  credit
590530         W  mastercard  credit
590531         R        visa  credit
590532         W  mastercard   debit
590533         W        visa   debit
590534         C  mastercard   debit
590535         W        visa   debit
590536         W  mastercard   debit
590537         W  mastercard   debit
590538         W  mastercard   debit
590539         W  mastercard  credit

[590540 rows x 3 columns]

In [29]:
train_full_df=train_full_df._get_numeric_data()
train_full_df=train_full_df.dropna()

len(train_full_df[train_full_df["isFraud"]==1])/len(train_full_df)*100

3.46278261170406

In [0]:
x_full_df=train_full_df.drop(["isFraud"],axis=1)
y_full_df=train_full_df["isFraud"]

In [31]:
x_full_df.tail()

        TransactionID  TransactionDT  ...  debit  debit or credit
590534        3577534       15811030  ...      1                0
590536        3577536       15811049  ...      1                0
590537        3577537       15811079  ...      1                0
590538        3577538       15811088  ...      1                0
590539        3577539       15811131  ...      0                0

[5 rows x 112 columns]

In [32]:
y_full_df.tail()

590534    0
590536    0
590537    0
590538    0
590539    0
Name: isFraud, dtype: int64

In [0]:
X_train,X_test,y_train,y_test=train_test_split(x_full_df,y_full_df,test_size=0.50)

In [0]:
from sklearn.linear_model import LogisticRegression  
from sklearn.preprocessing import StandardScaler  

from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

from sklearn.metrics import recall_score
from sklearn.metrics import accuracy_score

In [35]:
lr = LogisticRegression(solver='lbfgs')  
lr.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [36]:
lr.score(X_test, y_test)

0.9656143507066374

In [0]:
y_pred=lr.predict(X_test)

In [39]:
pd.crosstab(y_test, y_pred, rownames=['True'], colnames=['Predicted'], margins=True)

Predicted       0     All
True
0          279106  279106
1            9939    9939
All        289045  289045